name: 'Update Issue status Action'
description: 'Update the issue status when comment created'
inputs:
  project:
    description: 'The name of the GitHub Project'
    required: true
  column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
  issue:
    description: 'The number of the issue'
    required: true
  token:
    description: 'The token to use to access the GitHub API'
    required: true
runs:
  using: 'node16'
  main: 'src/index.js'